export enum RequestStatus {
  CREATED = "CREATED",
  PROCESSING = "PROCESSING",
  PARTIAL_RESULTS = "PARTIAL_RESULTS",
  READY_FOR_REVIEW = "READY_FOR_REVIEW",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}
